# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "" # Leave empty: logo says NeuroML
author: NeuroML contributors
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/NeuroML/Documentation  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  favicon: images/favicon.ico
  google_analytics_id: "" # To be added
  home_page_in_navbar: false


# Binder bits
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url: https://mybinder.org
