# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "NeuroML Documentation" # Leave empty: logo says NeuroML
author: "NeuroML contributors"
logo: images/logo.png

# List bibtex source file
bibtex_bibfiles:
  - Reference/references.bib

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: neuroml-documentation.tex
    use_jupyterbook_latex: true
  latex_engine: pdflatex

# Information about where the book exists on the web
repository:
  url: https://github.com/NeuroML/Documentation  # Online location of your book
  path_to_book: source  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  favicon: images/favicon.ico
  google_analytics_id: "" # To be added
  home_page_in_navbar: false


# Binder bits
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic"
  thebe: true

# Extra parsing options
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
  myst_url_schemes          : [mailto, http, https]

sphinx:
  config:
    pygments_style: "tango"
    latex_elements: # https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/276#issuecomment-1102154800
      preamble: |
        % make phantomsection empty inside figures
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
