name: Publish

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "37 22 * * 1,3,5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Set up JDK 11 for jNeuroML etc
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install -r requirements-book.txt
        sudo apt-get update -y
        sudo apt-get install build-essential -y
        sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-xetex latexmk -y
    - name: Update buf_size in texmf.cnf
      run: |
        kpsewhich -a texmf.cnf
        grep -i "^buf_size" `kpsewhich -a texmf.cnf`
    - name: Disable building jupyter-books
      run: |
        sed -i "s/execute_notebooks.*/execute_notebooks: 'off'/" source/_config.yml
    - name: Run jupyter-book
      run: |
        jupyter-book clean ./source
        jupyter-book build ./source  --builder pdflatex
        mv ./source/_build/latex/neuroml-documentation.pdf ./source/_static/files/
        jupyter-book build ./source
    - name: Update locations in 404 page
      run: |
        sed -i 's|src="\([[:alnum:]_]\)|src="/\1|g' ./source/_build/html/404.html
        sed -i 's|href="\([[:alnum:]_]\)|href="/\1|g' ./source/_build/html/404.html
        # if we also replaced "http.." with "/http..", undo that
        sed -i 's|href="/http|href="http|g' ./source/_build/html/404.html
        sed -i 's|src="/http|src="http|g' ./source/_build/html/404.html
    - name: Import to GitHub pages
      run: |
        ghp-import -c "docs.neuroml.org" -n -p -f ./source/_build/html
